/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BloodBankManagment;

import PackageClasses.Donor;
import PackageClasses.DonorDirectory;
import static PackageClasses.DonorDirectory.donors;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import static java.lang.System.in;
import java.util.ArrayList;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Hp
 */
public class AddNewDonor extends javax.swing.JFrame  {

//    private static void addDonor(Donor d) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    /**
     * Creates new form AddNewDonor
     * 
     * @param DonorId
     * @param FullName
     */
 
    public AddNewDonor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DonorId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FullName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FatherName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        MotherName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        MobileNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DateOfBirth = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Gender = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        BloodGroup = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CompleteAddress = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        saveButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blood bank Managment System");
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Add New Donor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 21, 443, 35));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 706, 10));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 132, 41, -1));

        jLabel3.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("New Donor Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 97, -1, -1));

        DonorId.setBackground(new java.awt.Color(255, 255, 255));
        DonorId.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        DonorId.setForeground(new java.awt.Color(0, 0, 0));
        DonorId.setCaretColor(new java.awt.Color(0, 0, 0));
        DonorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonorIdActionPerformed(evt);
            }
        });
        getContentPane().add(DonorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 90, 212, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Full Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 154, 85, -1));

        FullName.setBackground(new java.awt.Color(255, 255, 255));
        FullName.setForeground(new java.awt.Color(0, 0, 0));
        FullName.setCaretColor(new java.awt.Color(0, 0, 0));
        FullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullNameActionPerformed(evt);
            }
        });
        getContentPane().add(FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 150, 193, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Father Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, -1, -1));

        FatherName.setBackground(new java.awt.Color(255, 255, 255));
        FatherName.setForeground(new java.awt.Color(0, 0, 0));
        FatherName.setCaretColor(new java.awt.Color(0, 0, 0));
        FatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherNameActionPerformed(evt);
            }
        });
        getContentPane().add(FatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 196, 193, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Mother Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 253, 97, -1));

        MotherName.setBackground(new java.awt.Color(255, 255, 255));
        MotherName.setForeground(new java.awt.Color(0, 0, 0));
        MotherName.setCaretColor(new java.awt.Color(0, 0, 0));
        MotherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotherNameActionPerformed(evt);
            }
        });
        getContentPane().add(MotherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 249, 193, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Mobile Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 299, -1, -1));

        MobileNumber.setBackground(new java.awt.Color(255, 255, 255));
        MobileNumber.setForeground(new java.awt.Color(0, 0, 0));
        MobileNumber.setCaretColor(new java.awt.Color(0, 0, 0));
        MobileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileNumberActionPerformed(evt);
            }
        });
        getContentPane().add(MobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 295, 193, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Date of Birth");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 339, 97, -1));

        DateOfBirth.setBackground(new java.awt.Color(255, 255, 255));
        DateOfBirth.setForeground(new java.awt.Color(0, 0, 0));
        DateOfBirth.setCaretColor(new java.awt.Color(0, 0, 0));
        DateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateOfBirthActionPerformed(evt);
            }
        });
        getContentPane().add(DateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 335, 193, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 156, 106, -1));

        Email.setBackground(java.awt.Color.white);
        Email.setForeground(new java.awt.Color(0, 0, 0));
        Email.setCaretColor(new java.awt.Color(0, 0, 0));
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 150, 220, -1));

        jLabel10.setBackground(new java.awt.Color(0, 153, 153));
        jLabel10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Gender");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 375, 74, -1));

        Gender.setBackground(new java.awt.Color(51, 51, 51));
        Gender.setForeground(new java.awt.Color(255, 255, 255));
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "others" }));
        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 375, 193, -1));

        jLabel11.setBackground(new java.awt.Color(0, 102, 102));
        jLabel11.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Blood Group");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 202, 106, -1));

        BloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        getContentPane().add(BloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 197, 220, -1));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("City");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 255, 106, -1));

        City.setBackground(java.awt.Color.white);
        City.setForeground(new java.awt.Color(0, 0, 0));
        City.setCaretColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 249, 220, -1));

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Complete Address");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 301, 122, -1));

        CompleteAddress.setBackground(java.awt.Color.white);
        CompleteAddress.setColumns(20);
        CompleteAddress.setForeground(new java.awt.Color(0, 0, 0));
        CompleteAddress.setRows(5);
        CompleteAddress.setCaretColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(CompleteAddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 295, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 419, 706, 10));

        saveButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 0, 0));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodBankManagment/save.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 435, 96, 39));

        jButton2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodBankManagment/Update details.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 435, 107, 39));

        jButton3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodBankManagment/Exit application.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 435, 106, 39));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodBankManagment/all page background image.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 700, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void DonorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonorIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DonorIdActionPerformed

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
         // TODO add your handling code here:
         
        try {
            Donor d =    new Donor();
            d.setDonorId(DonorId.getText());
            d.setFullName(FullName.getText());
            d.setLocation(City.getText());
            d.setFatherName(FatherName.getText());
            d.setMotherName(MotherName.getText());
            d.setMobileNumber(MobileNumber.getText());
            d.setEmail(Email.getText());
            d.setBloodGroup((String) BloodGroup.getSelectedItem());
            d.setCity(City.getText());
            d.setCompleteAddress(CompleteAddress.getText());
            d.setDateOfBirth(DateOfBirth.getText());
            d.setGender((String) Gender.getSelectedItem());
            DonorDirectory.addDonor(d);
            this.setVisible(false);
            home obj = new home();
            obj.setVisible(true);

            JOptionPane.showMessageDialog(null, "Donor information saved successfully!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
        }
    
    }//GEN-LAST:event_saveButtonActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddNewDonor().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void FullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNameActionPerformed
        // TODO add your handling code here:
        FullName.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String text = ((JTextField) input).getText();
                if (text.matches("^[A-Za-z\\s]+$")) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid name. Only letters and spaces are allowed.");
                    return false;
                }
            }
        });
    }//GEN-LAST:event_FullNameActionPerformed

    private void FatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherNameActionPerformed
        // TODO add your handling code here:
        FatherName.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String text = ((JTextField) input).getText();
                if (text.matches("^[A-Za-z\\s]+$")) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid name. Only letters and spaces are allowed.");
                    return false;
                }
            }
        });
    }//GEN-LAST:event_FatherNameActionPerformed

    private void MotherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotherNameActionPerformed
        // TODO add your handling code here:
        MotherName.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String text = ((JTextField) input).getText();
                if (text.matches("^[A-Za-z\\s]+$")) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid name. Only letters and spaces are allowed.");
                    return false;
                }
            }
        });
    }//GEN-LAST:event_MotherNameActionPerformed

    private void MobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileNumberActionPerformed
        // TODO add your handling code here:
        MobileNumber.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String text = ((JTextField) input).getText();
                if (text.matches("^\\d{11}$")) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid phone number. Must be 10 digits.");
                    return false;
                }
            }
        });

    }//GEN-LAST:event_MobileNumberActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
        Email.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String text = ((JTextField) input).getText();
                if (text.matches("^[\\w.-]+@[\\w.-]+\\.\\w{2,4}$")) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid email format.");
                    return false;
                }
            }
        });
    }//GEN-LAST:event_EmailActionPerformed

    private void DateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateOfBirthActionPerformed
         DateOfBirth.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String text = ((JFormattedTextField) input).getText();
                if (text.matches("^\\d{2}-\\d{2}-\\d{4}$")) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid date format. Use dd-MM-yyyy.");
                    return false;
                }
            }
        });
    }//GEN-LAST:event_DateOfBirthActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewDonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BloodGroup;
    private javax.swing.JTextField City;
    private javax.swing.JTextArea CompleteAddress;
    private javax.swing.JTextField DateOfBirth;
    private javax.swing.JTextField DonorId;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FatherName;
    private javax.swing.JTextField FullName;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField MobileNumber;
    private javax.swing.JTextField MotherName;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
