/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BloodBankManagment;

import PackageClasses.Donor;
import PackageClasses.DonorDirectory;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class SearchDonor extends javax.swing.JFrame {

    /**
     * Creates new form SearchDonor
     */
    public SearchDonor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donorLocation = new javax.swing.JTextField();
        DonorSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DonorList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blood Bank Managment System");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donorLocation.setBackground(new java.awt.Color(255, 255, 255));
        donorLocation.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(donorLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 71, 269, -1));

        DonorSearch.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        DonorSearch.setForeground(new java.awt.Color(0, 0, 0));
        DonorSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodBankManagment/search1.png"))); // NOI18N
        DonorSearch.setText("Search");
        DonorSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonorSearchActionPerformed(evt);
            }
        });
        getContentPane().add(DonorSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 68, 113, -1));

        DonorList.setBackground(new java.awt.Color(255, 255, 255));
        DonorList.setForeground(new java.awt.Color(0, 0, 0));
        DonorList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(DonorList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 694, 316));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodBankManagment/Location.png"))); // NOI18N
        jLabel1.setText("Address");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 74, 125, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Search Donor By Address");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 6, 374, -1));

        jButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodBankManagment/Exit application.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 440, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BloodBankManagment/all page background image.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DonorSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonorSearchActionPerformed
        // TODO add your handling code here:
        
        String [] cols = {"ID","Name","Father Name","Mother Name","MObile Number","Date of Birth","Gender","Email","Blood group","LOcation","Address"};
        ArrayList<Donor> donors = DonorDirectory.searchDonor(donorLocation.getText());
        DefaultTableModel model = (DefaultTableModel) DonorList.getModel();
        model.setColumnIdentifiers(cols);
        String [] temp = new String[11];int j=0;
        for (int i = 0; i < donors.size(); i++) {
            temp[j++] = donors.get(i).getDonorId();
            temp[j++] = donors.get(i).getFullName();
            temp[j++] = donors.get(i).getFatherName();
            temp[j++] = donors.get(i).getMotherName();
            temp[j++] = donors.get(i).getMobileNumber();
            temp[j++] = donors.get(i).getDateOfBirth();
            temp[j++] = donors.get(i).getGender();
            temp[j++] = donors.get(i).getEmail();
            temp[j++] = donors.get(i).getBloodGroup();
            temp[j++] = donors.get(i).getCity();
            temp[j] = donors.get(i).getCompleteAddress();
            j=0;
            model.addRow(temp);
        }
        DonorList.setModel(model);
        
        
        
        
    }//GEN-LAST:event_DonorSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchDonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DonorList;
    private javax.swing.JButton DonorSearch;
    private javax.swing.JTextField donorLocation;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
